mod merge;
mod split;
mod compress;
mod encrypt;
mod pages;
mod images;
mod watermark;
mod thumbnails;
mod pdf_ops;
mod reader;
mod annotations;

pub use merge::merge;
pub use split::split;
pub use compress::compress;
pub use encrypt::{encrypt, decrypt};
pub use pages::{delete_pages, extract_pages, rotate_pages, reorder_pages, page_count};
pub use images::{pdf_to_images, images_to_pdf};
pub use watermark::{add_watermark, WatermarkOptions};
pub use thumbnails::pdf_page_thumbnails;
pub use reader::render_page;
pub use annotations::{load_annotations, save_annotations, PageAnnotations};